-- Run this once in the Supabase SQL editor before deploying the
-- /curator-picks and /admin/curator-picks routes -- they read and write
-- this table and will 500 on every call until it exists.

create table if not exists curator_picks (
    id bigint generated by default as identity primary key,
    series_id bigint not null references series(id) on delete cascade,
    blurb text,
    is_feature boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    unique (series_id)
);

-- The app already cleans this table up itself before deleting a series
-- (DELETE /admin/series/:id), same defensive-cleanup-before-delete
-- pattern used for every other series-referencing table in this codebase
-- rather than relying on this cascade -- it's here as a safety net only,
-- in case a series is ever removed some other way.
