-- Run this once in the Supabase SQL editor before deploying the
-- /admin/import/run and /admin/import/status routes -- they read and
-- write this table and will error/silently no-op on every call until it
-- exists. The code has referenced "migrations/import_runs.sql" in a
-- comment for a while, but the file itself was never actually committed --
-- this is that file, reconstructed from the exact columns the code reads
-- and writes (src/index.ts: startImportRun, reconcileOrphanedImportRun,
-- persistImportLog, GET /admin/import/status).

create table if not exists import_runs (
    id bigint generated by default as identity primary key,
    status text not null default 'running', -- 'running' | 'success' | 'error' | 'interrupted'
    limit_per_type integer,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    exit_code integer,
    error_message text,
    log text
);

create index if not exists import_runs_started_at_idx on import_runs (started_at desc);
