-- Run this once in the Supabase SQL editor before deploying the
-- /collections and /admin/collections routes -- they read and write these
-- tables and will error/404 on every call until they exist.
--
-- One table holds both kinds of collection, distinguished by is_curated:
--   is_curated = false -> a regular user's personal collection
--     (owner_user_id is that user; managed only through /collections/* by
--     its owner)
--   is_curated = true  -> an admin-curated collection, shown publicly
--     (owner_user_id is whichever admin created it, kept for audit only;
--     managed only through /admin/collections/*, never through the
--     owner-only /collections/* routes -- see requireOwnerOrOwnerOnly-style
--     checks in src/index.ts)
-- Splitting these into two tables would just duplicate the same
-- title/description/series-list shape twice; a single is_curated flag plus
-- separate route namespaces (like tags vs genres already do for similarly
-- shaped things) keeps this in one place.

create table if not exists collections (
    id bigint generated by default as identity primary key,
    owner_user_id bigint references users(id) on delete set null,
    title text not null,
    description text,
    is_curated boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists collection_series (
    collection_id bigint not null references collections(id) on delete cascade,
    series_id bigint not null references series(id) on delete cascade,
    sort_order integer not null default 0,
    added_at timestamptz not null default now(),
    primary key (collection_id, series_id)
);

create index if not exists collections_owner_idx on collections (owner_user_id) where is_curated = false;
create index if not exists collections_curated_idx on collections (is_curated);
create index if not exists collection_series_series_idx on collection_series (series_id);

-- Same defensive-cleanup-before-delete pattern used everywhere else in this
-- codebase (see DELETE /admin/series/:id) means the app itself removes
-- collection_series rows before deleting a series, rather than relying on
-- this cascade -- it's here as a safety net only.
