-- Run this once in the Supabase SQL editor before deploying the rank-
-- snapshot job and GET /series's rank_trend field (H2-01) -- both read
-- and write this table and will 500 / silently return no trend data
-- until it exists.
--
-- H2-01: the Home tab's trending arrows were a hardcoded
-- ['up','down','up','up','flat'] array applied by card position, with no
-- relationship to any real signal. This table gives "trend" something
-- real to be computed from: POST /admin/rank-snapshots/run
-- (src/routes/admin/rankSnapshots.ts) computes a popularity rank for
-- every rated series and inserts one row per series for the current day.
-- GET /series then compares today's snapshot to the most recent prior
-- one to derive rank_trend ('up' | 'down' | 'flat' | 'new') --
-- see src/services/rankSnapshots.ts.
--
-- One row per (series_id, snapshot_date) -- upserted on that pair so
-- re-running the job the same day updates today's row instead of
-- duplicating it (there's no cron scheduler in this app yet; the job is
-- triggered manually or by an external scheduler hitting the admin
-- route, and may reasonably be run more than once in a day).

create table if not exists series_rank_snapshots (
    id bigint generated by default as identity primary key,
    series_id bigint not null references series(id) on delete cascade,
    snapshot_date date not null default current_date,
    rank integer not null,
    score numeric not null,
    created_at timestamptz not null default now(),
    unique (series_id, snapshot_date)
);

create index if not exists series_rank_snapshots_snapshot_date_idx
    on series_rank_snapshots (snapshot_date desc);

-- series_rank_snapshots has been added to the cleanupTables list in
-- restore/reject (A1-01/A1-02) and DELETE /admin/series/:id, same as
-- every other series-referencing table -- this codebase deletes FK
-- dependents explicitly rather than relying on ON DELETE CASCADE (see
-- those routes' own comments), so the cascade above is a safety net
-- only, not the real cleanup path.
