-- Run this once in the Supabase SQL editor before deploying the
-- gamification service (H2-03) -- POST /ratings, POST /watchlist, and
-- GET /me/gamification all read/write these tables and will error (the
-- first two only on the fire-and-forget gamification step, logged but
-- not failing the request -- see services/gamification.ts) until they
-- exist.
--
-- H2-03: Bloom Journey (level/XP) and This Week's Journey (discovery
-- streak) were both 100% MOCK_BLOOM_JOURNEY / MOCK_WEEKLY_JOURNEY --
-- every signed-in user saw the identical level, XP, and streak. Three
-- tables back this instead of one, because "current level/XP/streak"
-- (a single row, cheap to read on every Home load) and "which specific
-- days had activity" (a growing history, only ever queried for the
-- current week) and "was XP already awarded today" (a dedupe check,
-- never queried by anything else) are three different access patterns,
-- not one denormalized blob.

-- One row per user: the fast-to-read current snapshot GET
-- /me/gamification serves from. xp is lifetime cumulative XP; level and
-- its label are DERIVED from xp at read time (see
-- computeLevelProgress() in services/gamification.ts), not stored here
-- -- storing a derived value invites the two drifting apart if the
-- leveling formula/thresholds are ever tuned later (which the frontend
-- comment already flags them as: "illustrative").
create table if not exists user_stats (
    user_id bigint primary key references users(id) on delete cascade,
    xp integer not null default 0,
    current_streak_days integer not null default 0,
    longest_streak_days integer not null default 0,
    last_activity_date date,
    updated_at timestamptz not null default now()
);

-- One row per (user, calendar day) that had any qualifying activity
-- (a rating or a watchlist change). This Week's Journey's 7-day M-S row
-- is built by querying this table for the current week -- see
-- getWeekProgress() in services/gamification.ts. Deliberately NOT the
-- same thing as "days that earned XP" (user_xp_events below) -- a
-- second rating on a day that already earned rating XP still counts as
-- that day's discovery activity for the streak, it just doesn't pay out
-- twice.
create table if not exists user_activity_days (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    activity_date date not null,
    created_at timestamptz not null default now(),
    unique (user_id, activity_date)
);

create index if not exists user_activity_days_user_date_idx
    on user_activity_days (user_id, activity_date desc);

-- One row per (user, day, action kind) that XP was actually paid out
-- for. The unique constraint IS the dedupe mechanism: recordActivity()
-- tries to insert a row before crediting XP, and a unique-violation
-- means "already paid out today for this kind" -- so someone re-rating
-- the same series five times in an afternoon (or five different series)
-- earns today's rating XP once, not five times. Never queried outside
-- of that insert-and-check -- this is a ledger for the dedupe logic,
-- not a display feed.
create table if not exists user_xp_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    event_date date not null,
    kind text not null,
    xp_amount integer not null,
    created_at timestamptz not null default now(),
    unique (user_id, event_date, kind)
);

-- All three cascade on user delete, and DELETE /admin/users/:id also
-- explicitly deletes from them before deleting the users row itself
-- (same explicit-cleanup-before-delete convention ratings/user_lists
-- already follow there) -- the cascades exist as a safety net, not as
-- the primary cleanup path.
